name:                basicvarianttools
version:             0.1.0.0
github:              "githubuser/basicvarianttools"
license:             BSD3
author:              "Matthew Mosior"
maintainer:          "mattm.github@gmail.com"
copyright:           "Matthew Mosior, 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/basicvarianttools#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3.3.2
- extra >= 1.6.15
- split >= 0.2.3.3
- temporary >= 1.3
- process >= 1.6.5.0
- boxes >= 0.1.5
- regex-tdfa >= 1.2.3.2
- regex-compat >= 0.95.1
- optparse-applicative >= 0.14.3.0
- filepath >= 1.4.2.1
- random >= 1.1
- tasty >= 1.2.2
- tasty-quickcheck >= 0.10.1
- tasty-hunit >= 0.10.0.2

library:
  source-dirs: src
  default-extensions:
    - MultiWayIf
    - ScopedTypeVariables

executables:
  basicvarianttools-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - basicvarianttools

tests:
  basicvarianttools-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - basicvarianttools
